pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh """
        echo "Repo Owner: ${repoOwner}"
        echo "Repo Name : ${repoName}"
        echo "Repo Creds: ${repoCreds}"
        echo "Deploy to .... "
        """
      }
    }
    stage('Deploy') {
          when {
            expression {
                return deployApp
            }
             beforeOptions true
          }
          steps {
            sh """
            echo "deploying to"
            """
          }
        }
  }
}
