pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh """
        echo "Repo Owner: ${repoOwner}"
        echo "Repo Name : ${repoName}"
        echo "Repo Creds: ${repoCreds}"
        """
      }
    }
  }
}
